"""create user_favorite_operators table

Revision ID: aefe9aef5443
Revises: 50d3fd50f54c
Create Date: 2025-02-19 12:59:39.529636

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "aefe9aef5443"
down_revision = "50d3fd50f54c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_favorite_operators",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("operator_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["operator_id"], ["operators.display_number"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_favorite_operators")
    # ### end Alembic commands ###
